dataset: imagenet
optimizer: re
out_dir: docs/re_run
search:
  acq_fn_optimization: mutation
  acq_fn_type: its
  checkpoint_freq: 5000
  constrained: true
  debug_predictor: false
  encoding_type: path
  epochs: 100
  fidelity: 200
  k: 25
  latency: 1000
  max_mutations: 1
  model_size: 10000000000.0
  num_arches_to_mutate: 2
  num_candidates: 100
  num_ensemble: 3
  num_init: 10
  population_size: 30
  predictor_type: feedforward
  sample_size: 10
  seed: 0
search_space: ofa
seed: 0
