dataset: imagenet
optimizer: re
out_dir: re_run_0
search:
  acq_fn_optimization: random_sampling
  acq_fn_type: its
  batch_size: 256
  checkpoint_freq: 5000
  cutout: false
  cutout_length: 16
  cutout_prob: 1.0
  data_size: 25000
  encoding_type: adjacency_one_hot
  epochs: 100
  fidelity: 200
  k: 20
  max_mutations: 1
  num_arches_to_mutate: 5
  num_candidates: 200
  num_ensemble: 3
  num_init: 20
  population_size: 30
  predictor_type: rf
  sample_size: 10
  train_portion: 0.7
search_space: OnceForAll
seed: 2
