dataset: imagenet
optimizer: re
out_dir: docs/re_run
search:
  acq_fn_optimization: random_sampling
  acq_fn_type: its
  batch_size: 256
  checkpoint_freq: 5000
  constraint: parameters
  cutout: false
  cutout_length: 16
  cutout_prob: 1.0
  data_size: 25000
  efficiency: 25.181838989257812
  encoding_type: adjacency_one_hot
  epochs: 300
  fidelity: 200
  k: 20
  max_mutations: 1
  num_arches_to_mutate: 5
  num_candidates: 100
  num_ensemble: 3
  num_init: 20
  population_size: 30
  predictor_type: rf
  sample_size: 10
  seed: 0
  train_portion: 0.7
search_space: ofa
seed: 0
